name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: |
          cd example
          flutter pub get

      - run: |
          cd example
          flutter build apk

  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - run: |
          cd example
          flutter pub get

      - run: |
          cd example
          flutter build ios --no-codesign
