name: Publish to pub.dev

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Publish package
        run: dart pub publish  --dry-run
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
